export { default as alfajoresChocolate } from './alfajoresChocolate.jpeg';
export { default as alfajoresCoco } from './alfajoresCoco.jpeg';
export { default as bizcochos } from './bizcochos.jpeg';
export { default as budinChocolate } from './budinChocolate.jpeg';
export { default as logo } from './logo.jpeg';
export { default as medialunasChocolate } from './medialunasChocolate.jpeg';
export { default as medialunasCoco } from './medialunasCoco.jpeg';
export { default as budinNZN } from './budinNZN.jpeg';
export { default as panIntegralSemillas } from './panIntegralSemillas.jpeg';
export { default as email} from'./email.png';
export {default as facebook } from './facebook.png';
export {default as instagram } from './instagram.png';
export {default as whatsapp} from './whatsapp.png';
export {default as twitter} from './twitter.png';
export {default as logoSpan} from './logoSpan.jpeg';
export {default as veganSpan} from './vegano.jpeg';
export {default as medialunasRellenasCOCO} from './medialunasRellenasCOCO.jpg';
export {default as carrotCake} from './carrotCake.jpg';
export {default as invertedAppleCake} from './invertedAppleCake.jpg';
export {default as budinBananaChoco} from './budinBananaChoco.jpg';
export {default as budinChocoCoco } from './budinChocoCoco.jpg';
export {default as budinManzana } from './budinManzana.jpg';
export {default as panIntegralCenteno } from './panIntegralCenteno.jpg';
